# Generated by Django 6.0.3 on 2026-06-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(blank=True, default="", max_length=200)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("focus", "Focus"),
                            ("short_break", "Short Break"),
                            ("long_break", "Long Break"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField()),
                ("completed", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
